### ISSUE TITLE
Python-3 support

### ISSUE THREAD

**Issue by jedbrown** [geodynamics/spatialdata#8]
Python2 EOL is fast approaching and the present codebase is python2-only. [futurize](https://python-future.org/futurize.html) is a useful tool for converting a python2 codebase to Python3.

I have some experience using futurize, but I can't currently run the test suite. My system has the default /usr/bin/python as python3. While the autoconf script finds `python2` correctly, it seems to be running `pytest` rather than `pytest2`, thus tests fail to import the python2 module. I'm not sure what is intended here and haven't dug in to debug yet.

**Comment by knepley** [comment]
Yes, we discussed this at the meeting and put it as a high development priority. I directed everyone to the PETSc PR with the Python-3 upgrade. Our only real stumbling block here is Pyre.

**Comment by jedbrown** [comment]
I'd be happy to help with `futurize`, but these packages aren't familiar to me and I'd need a working test suite. (I suppose it would probably work if I ran inside an older container.)

**Comment by baagaard-usgs** [comment]
Needs to be coordinated with updating Python 3 for Pythia, nemesis, and PyLith. See https://github.com/geodynamics/pylith/issues/31, https://github.com/geodynamics/nemesis/issues/2, https://github.com/geodynamics/pythia/issues/4.
