### ISSUE TITLE
SWIG 4.0 support

### ISSUE THREAD

**Issue by jedbrown** [geodynamics/spatialdata#9]
SWIG 3.0.2 (the current max supported version) is 5 years old now (the latest release is 4.0). Installing this heirloom is an awkward dependency on modern machines. I tried just editing `configure.ac` and got an error-free build, but haven't been able to test (cf. #8).

**Comment by baagaard-usgs** [comment]
See https://github.com/geodynamics/pylith/issues/28 for a description of the problem. Builds with later versions of SWIG proceed, but we have problems with Pyre stuff not working. I spent about a day trying to figure this out, but couldn't out the cause of the problem.
